

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE, echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(nbastatR)
library(readr)
library(teamcolors)
library(reactablefmtr)
library(MetBrewer)
library(htmltools)
library(tibbletime)
library(crosstalk)

```


```{r}

df_team_logs <- game_logs(seasons = 2022, result_types = "team", season_types = "Regular Season") 

```

```{r}

recode_key <- c(NOH = "NO", NJN = "BKN")
recode_key_2 <- c("Los Angeles Clippers" = "LA Clippers")
remove <- c("New Jersey Nets", "Charlotte Bobcats", "Seattle SuperSonics", "New Orleans Hornets")

```

```{r}

western_conference <- c("Northwest", "Pacific", "Southwest")

eastern_conference <- c("Southeast", "Atlantic", "Central")

rolling_mean <- rollify(mean, window = 10)

```


```{r}

df_team_names <- dictionary_bref_teams() %>% 
  filter(seasonLast == 2022) %>% 
  select(nameTeamBREF, slugTeamBREF) %>% 
  mutate(slugTeamBREF = recode(slugTeamBREF, !!!recode_key),
         nameTeamBREF = recode(nameTeamBREF, !!!recode_key_2))

df_team_logos <- teamcolors %>% 
  filter(league == "nba") %>%
  mutate(name = recode(name, !!!recode_key_2)) %>% 
  mutate(
    img_name = str_replace(logo, ".*[/]([^.]+)[.].*", "\\1"),
    img_name = glue::glue("https://raw.githubusercontent.com/schmid07/R-Reactable-NBA-Raptor/main/logos/{img_name}.png"),
    conference = fct_collapse(division, 
                              "Western Conference" = western_conference,
                              "Eastern Conference" = eastern_conference))

```

```{r}

# calculating 10 game rolling average
df_rolling_avg <- df_team_logs %>% 
  group_by(nameTeam) %>%
  mutate(mean_10 = rolling_mean(plusminusTeam)) %>% 
  filter(numberGameTeamSeason > 9) %>% 
  # rolling avg. needs to be in a list for the table
  mutate(mean_10 = list(mean_10)) %>% 
  ungroup() %>% 
  distinct(nameTeam, .keep_all = TRUE) %>% 
  select(nameTeam, mean_10)

# joining logos, rolling_avg calc and shortening team names
df_team_adj <- df_team_logs %>% 
  left_join(df_team_logos %>% 
              select(name, conference, img_name), 
            by = c("nameTeam" = "name")) %>% 
  left_join(df_team_names, by = c("nameTeam" = "nameTeamBREF")) %>% 
  left_join(df_rolling_avg)

df_win_ratio <- df_team_adj %>% 
  add_count(nameTeam, name = "games_played") %>% 
  add_count(nameTeam, wt = as.integer(isWin), name = "wins") %>% 
  mutate(points_allowed = ptsTeam - plusminusTeam) %>% 
  group_by(slugTeamBREF, img_name, games_played, wins, mean_10, conference) %>% 
  summarise(
    across(c(ptsTeam, points_allowed), sum)) %>% 
  ungroup() %>% 
  mutate(points_diff = round((ptsTeam - points_allowed) / games_played, 1),
         ppg = round(ptsTeam / games_played, 1),
         opp_ppg = round(points_allowed / games_played, 1),
         # pythagorean expectation; for more info see here https://en.wikipedia.org/wiki/Pythagorean_expectation and here https://fansided.com/2017/09/18/nylon-calculus-expected-win-totals-distribution/
         expected_wins = round(ptsTeam ^ 14 / (ptsTeam ^ 14 + points_allowed ^ 14) * games_played),
         win_diff = expected_wins - wins) %>% 
  select(slugTeamBREF, conference, img_name, wins, expected_wins, win_diff, ppg, opp_ppg, points_diff, mean_10)
  
```

```{r}
crosstalk_data <- SharedData$new(df_win_ratio)

conference_filter <- filter_select(
  id = "conference",
  label = "CONFERENCE",
  sharedData = crosstalk_data,
  group = ~ conference
)
```



```{r}
options(reactable.theme = reactableTheme(
  backgroundColor = "#fafafa",
  borderColor = "#BEBEBE",
  headerStyle = list(
        "&:hover[aria-sort]" = list(background = "#E8E8E8"),
        "&[aria-sort='ascending'], 
        &[aria-sort='descending']" = list(background = "#C8C8C8"),
        borderWidth = "2px"
)))

pal <- met.brewer(name = "OKeeffe1")
```


```{r}
tbl_react <- reactable(crosstalk_data,
          pagination = FALSE,
          showSortIcon = FALSE,
          defaultSorted = list(win_diff = "desc"),
          defaultColDef = colDef(align = "center"),
          height = 700,
          columns = list(
            slugTeamBREF = colDef(
              show = FALSE
              ),
            img_name = colDef(
              cell = embed_img(df_win_ratio, height = "30", width = "45",
                               label = "slugTeamBREF"),
              name = "Team",
              maxWidth = 80),
            conference = colDef(
              show = FALSE
            ),
            wins = colDef(
              name = "W",
              maxWidth = 50
            ),
            ppg = colDef(
              name = "PPG",
              maxWidth = 70
            ),
            opp_ppg = colDef(
              name = "OPP PPG",
              maxWidth = 100
            ),
            mean_10 = colDef(
              name = "TEN GAME ROLLING AVG (PTS +/-)",
              cell = react_sparkline(df_win_ratio,
                                     height = 40,
                                     decimals = 1,
                                     statline = "mean",
                                     label_size = ".9em",
                                     statline_label_size = ".9em",
                                     highlight_points = highlight_points(
                                       min = "red",
                                       max = "blue"),
                                     labels = c("min", "max"))
              ),
            points_diff = colDef(
              name = "DIFF",
              maxWidth = 50,
              cell = function(value) {
                if (value >= 0) paste0("+", value) else value
              },
              style = function(value) {
                color <- if (value > 0) {
                  "#008000"
                  } else if (value < 0) {
                    "#e00000"
                    }
                list(color = color)
              }
            ),
            expected_wins = colDef(
              name = "EXP W",
              maxWidth = 80
            ),
            win_diff = colDef(
              name = "W DIFF",
              maxWidth = 80,
              cell = color_tiles(df_win_ratio, pal)
                         )))

```


```{css, include = TRUE}

.table-wrap {
  box-shadow: 2px 3px 20px black;
  background-color: #fafafa;
  font-size: 17px;
  font-weight: 400;
  font-family: Fira Sans Condensed;
  padding: 20px 20px 20px 20px;  
}

.table-title {
  font-size: 42px;
  font-weight: 500;
  line-height: 1.7
}
.table-sub {
  font-size: 16px;
  color: #6e6b6b;
  font-weight: 400;
}

.table-dropdown {
  font-size: 16px;
  color: #6e6b6b;
}

.table-cap {
  font-size: 14px;
  font-weight: 200;
}

```

```{r}
title <- "Expected Wins - 2021/2022 Season"

subtitle_1 <- "The table shows actual wins versus expected wins and also shows a ten game rolling average of margin of victory/defeat through January 9th, 2022. Expected wins is derived from points scored and points allowed. The rolling average is derived from the average +/- points differential from the preceding ten games. The dotted line shows the average across all ten game intervals for the season."

subtitle_2 <- "Over the first ten games, the Cleveland Cavaliers, for example, were outscored by an average of .5 points per game, their minimum over any ten game stretch of the year. From games 22 to 31, they outscored opponents by an average of 16 points per game, their maximum for the year.  The average across all stretches of ten game intervals has been +6.6 points per game."  

caption <- "Bill Schmid @schmid_07 | Source: {nbastatR}"

```


```{r, include = TRUE}
ima <- here::here("nba_logo.png")

div(class = "table-wrap",
    br(),
    tags$img(src = ima,
             align = "right",
             width = "40px",
             height = "80px"),
    div(class = "table-title", title),
    div(class = "table-sub", subtitle_1),
    br(),
    div(class = "table-sub", subtitle_2),
    br(),
    div(class = "table-dropdown", 
        bscols(
          widths = c(4, 2, 2, 3),
          conference_filter
          )
    ),
    br(),
    tbl_react,
    div(class = "table-cap", 
        tags$span(style = "font-weight:500; line-height:2", "GLOSSARY"),
        br(),
        tags$span(style = "font-weight:400", "EXP W:"), 
        "Expected Wins",
        br(),
        tags$span(style = "font-weight:400", "W DIFF:"), 
        "Delta between Expected Wins and Actual Wins",
        br(),
        tags$span(style = "font-weight:400", "PPG:"), 
        "Points per game",
        br(),
        tags$span(style = "font-weight:400", "OPP PPG:"), 
        "Opponents points per game",
        br(),
        tags$span(style = "font-weight:400", "DIFF:"), 
        "Point differential between average ppg and opponents ppg"
        ),
        br(),
    div(class = "table-cap",
        tags$span(style = "font-weight:400", "TABLE:"), 
        caption)
)
```
